server:
  port: 8002

spring:
  application:
    name: "productManagementService"
  datasource:
    url: "jdbc:mysql://localhost:3306/products"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: TRACE

externalApis:
  userService:
    getCurrentUserUrl: "http://localhost:8080/api/auth/currentInfo"