server:
  port: 8003

spring:
  application:
    name: "cartManagementService"
  datasource:
    url: "jdbc:mysql://localhost:3306/cart"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: TRACE

externalApi:
  productService:
    getProductByIdUrl: "http://localhost:8080/api/products/{id}"
    updateProductUrl: "http://localhost:8080/api/products/{id}"
    searchProductsUrl: "http://localhost:8080/api/products/search"