server:
  port: 8004

spring:
  application:
    name: "paymentManagementService"
  datasource:
    url: "jdbc:mysql://localhost:3306/payment"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: TRACE

externalApis:
  cartService:
    getCartByIdUrl: "http://localhost:8080/api/cart/{cartId}";
  userService:
    getUserByIdUrl: "http://localhost:8080/api/users/{userId}"
    getCurrentUserUrl: "http://localhost:8080/api/users/{userId}"